# Generated by Django 3.2.6 on 2021-08-07 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePitchExercise',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notecheck.exercise')),
                ('clef', models.CharField(choices=[('treble', 'Treble'), ('bass', 'Bass')], default='treble', max_length=10)),
            ],
            bases=('notecheck.exercise',),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise',
        ),
    ]
