# Generated by Django 3.2.6 on 2021-08-07 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0002_auto_20210807_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='num_questions',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
