# Generated by Django 3.2.6 on 2021-08-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0003_auto_20210807_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='assignment created date'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.JSONField(null=True),
        ),
    ]
