# Generated by Django 3.2.6 on 2021-08-07 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0004_auto_20210807_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
