# Generated by Django 3.2.6 on 2021-09-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0007_rename_submission_submission_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
