# Generated by Django 3.2.6 on 2021-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0009_alter_submission_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepitchexercise',
            name='max_flats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notepitchexercise',
            name='max_sharps',
            field=models.IntegerField(default=0),
        ),
    ]
