# Generated by Django 3.2.6 on 2021-10-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0011_auto_20211006_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
