# Generated by Django 3.2.6 on 2021-10-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0012_exercise_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
