# Generated by Django 3.2.6 on 2021-11-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0014_intervalexercise_intervalsubmission_notepitchsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepitchexercise',
            name='answer_type',
            field=models.CharField(choices=[('notename_octave', 'Note pitch and octave (e.g. fis2)'), ('notename', 'Note pitch only (e.g. fis)')], default='notename_octave', max_length=50),
        ),
        migrations.AlterField(
            model_name='intervalexercise',
            name='answer_type',
            field=models.CharField(choices=[('interval_quantity', 'Interval quantity (e.g. 4)'), ('interval_quantity_quality', 'Interval quality and quantity (e.g. p4)'), ('fulltones', 'Fulltones and remaining semitone (e.g. 2.5)'), ('semitones', 'Semitones (e.g. 5)')], default='interval_quantity_quality', max_length=50),
        ),
        migrations.AlterField(
            model_name='intervalexercise',
            name='max_flats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='intervalexercise',
            name='max_sharps',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notepitchexercise',
            name='max_flats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notepitchexercise',
            name='max_sharps',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
