# Generated by Django 3.2.6 on 2021-11-25 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0016_scaleexercise_scalesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaleexercise',
            name='direction',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
