# Generated by Django 3.2.6 on 2021-11-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0017_scaleexercise_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scaleexercise',
            old_name='scale_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='scaleexercise',
            old_name='scale_shape',
            new_name='shape',
        ),
    ]
