# Generated by Django 3.2.6 on 2021-11-29 20:18

from django.db import migrations, models
import notecheck.score


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0018_auto_20211125_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepitchexercise',
            name='custom_pitches',
            field=models.JSONField(blank=True, decoder=notecheck.score.DiatonicPitchDecoder, default=list, encoder=notecheck.score.DiatonicPitchEncoder),
        ),
    ]
