# Generated by Django 3.2.6 on 2024-10-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecheck', '0018_auto_20211125_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalexercise',
            name='clef',
            field=models.CharField(choices=[('treble', 'Treble'), ('bass', 'Bass'), ('treblebass', 'Treble and bass')], default='treble', max_length=10),
        ),
        migrations.AlterField(
            model_name='notepitchexercise',
            name='clef',
            field=models.CharField(choices=[('treble', 'Treble'), ('bass', 'Bass'), ('treblebass', 'Treble and bass')], default='treble', max_length=10),
        ),
        migrations.AlterField(
            model_name='scaleexercise',
            name='clef',
            field=models.CharField(choices=[('treble', 'Treble'), ('bass', 'Bass'), ('treblebass', 'Treble and bass')], default='treble', max_length=10),
        ),
    ]
